### ISSUE TITLE
Enabled pin of TextureFX should act as bypass

### ISSUE THREAD

**Issue by azeno** [vvvv/VL.Stride#263]
Currently it simply disables the rendering so the output stays the same - this is not really what one'd expect. The input (or if connected the output texture) should be passed down.

**Comment by tebjan** [comment]
doesn't seem to work anymore, as reported in the chat.

**Comment by tebjan** [comment]
tested, works fine... maybe some VL wrappers don't do it correctly? anyways, as it's still experimental, I'm closing this.
