### ISSUE TITLE
Define spaces for IRenderer

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#268]
for interaction and events like in skia

**Comment by azeno** [comment]
- Add `WithinSpace` and `WithinCommonSpace` as already defined by VL.Skia
- Remove `Screen Space` pin on various renderers (like QuadRenderer, LineRenderer, etc.) and get rid of special shaders which were used by that pin

**Comment by gregsn** [comment]
`WithPhysicalScreenSpace`: Units (choose Pixels or DIP), choose Anchor 
`WithVirtualScreenSpace`: choose manual Size and Anchor, Help Text for `Width` `Height`: Explain negative values and 0. (Alternative: AutoWidth, AutoHeight, FlipX, FlipY.)

both have the option to multiply ontop of View and Projection or not.
`Ignore Existing View`
`Ignore Existing Projection`

off-topic:
WithRenderView should have an option to correct aspect of projection and viewprojection according to aspect ratio of current viewport

**Comment by tebjan** [comment]
We should discuss:
* always have the scale and offset available
* AutoWidthOrHeight mode that adapts to which dimension is greater, I think this is the mode most people want

**Comment by azeno** [comment]
@gregsn Add Offset to WithinPhyiscalScreenSpace and close!

**Comment by tebjan** [comment]
Looks like all is done, closing.
