### ISSUE TITLE
Spread pins and pin groups

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#298]
* create quest in VL Lang repo 
* in Stride don't use pin groups, except for Group and RootScene

**Comment by azeno** [comment]
Remove input group on Components input of Stride.Models nodes (like Sphere). Fix all help patches after.

**Comment by azeno** [comment]
@gregsn Please give Anton short intro what to do here.

**Comment by gregsn** [comment]
Spec A:
- Typically there is only the node that has no pin groups. All Spread inputs are exposed as is.
  Naming: no versioning
- As soon as this is sad to work with:
  - Rename the general-purpose node to Foo (General-Purpose) or (Spread) or (Spectral) or (Dynamic) ...
  - Add an easy-to-use node that takes now can take the easy sounding name.
    - Use a pin group on the one input that you want to use the feature on. Typically you shouldn't use many pin groups, as this is hard to use.

The user by that never is locked in (there is always the general purpose node), but typically uses the easy-to-use node.

**Comment by joreg** [comment]
Spec B:
- don't use pingroups except on RootScene and Group nodes
- don't add additional nodes with other version (pingroup)

**Comment by gregsn** [comment]
Spec A it is
