### ISSUE TITLE
Adding int or uint as shader input seems to not work

### ISSUE THREAD

**Issue by everyoneishappy** [vvvv/VL.Stride#313]
Was trying in a textureFX, not sure if issue is for shaders more broadly.   Causes all shader inputs to disappear and needs restart of vvvv to fix (f8/5 won't help)

**Comment by everyoneishappy** [comment]
on 2020.3.0.58

**Comment by azeno** [comment]
Just tested this on a TextureFX and both int as well as uint worked just fine. If it pops up again feel free to re-open.
