### ISSUE TITLE
CalcDispatchArgs1D calculates wrong? results for DispatchCount

### ISSUE THREAD

**Issue by mhusinsky** [vvvv/VL.Stride#329]
noticed this when porting a CS based pipet. 
![grafik](https://user-images.githubusercontent.com/3253299/98543456-d049d000-2292-11eb-8b4a-65d624bb75f9.png)

compare the results in this file:
[Pipet.zip](https://github.com/vvvv/VL.Stride/files/5510607/Pipet.zip)

**Comment by tebjan** [comment]
this discussion happened also in the chat. i wouldn't say it is wrong, it is a question of definition. so, do you want to force every shader author to take care of the reminder in the shader code or not?

if yes, each compute shader will have a size input and a size check inside. besides an extra line of code, GPUs hate branching... it will slow down the whole shader.

it is recommended, if possible, to use a count that is exactly a multiple of the thread count and then only use the results you need further down in the pipeline. it will require to manage two counts in the patch, but will literally save millions of checks on the GPU.

so while you linearly increase the count of, for example, particles, it will actually (behind the scenes) increase in 64 steps, for example.

![image](https://user-images.githubusercontent.com/1094716/98712342-788c9100-2386-11eb-9cf3-7431a0a6d808.png)

![image](https://user-images.githubusercontent.com/1094716/98712542-ba1d3c00-2386-11eb-96f7-65f7398ec771.png)

of course, every user should be able to use the workflow they want, so I think should be an option.

**Comment by tebjan** [comment]
@mhusinsky @rmtttt this got an update now. the solution was quite simple in the end: `CalcDispatchArgs` returns the one number higher than before unless the count is a multiple of the thread group size (using @rmtttt method). then there are new nodes called `QuantizeCount` that help you to calculate a GPU friendly count that removes the need for a size check on the GPU.

with these nodes, you can now patch all cases, I think.

note that there are minor pin renamings to use the same terminology everywhere. "Thread Group Count" is the argument for the `Dispatch` and "Thread Group Size" is the group size that is specified in the `[numthreads(X, Y, Z)]` attribute in the shader.
