### ISSUE TITLE
Light disappears if it's straight above its target

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.Stride#332]
Reported that a long time ago and the question came up during the 'Realtime graphics with Stride 3D – The Fundamentals' Workshop. So now the Issue.
See the Testpatch.
[LightPosition_Bug.zip](https://github.com/vvvv/VL.Stride/files/5517002/LightPosition_Bug.zip)

![image](https://user-images.githubusercontent.com/1189037/98670701-5b8a9a80-2353-11eb-8488-3158a7d5872a.png)

**Comment by tebjan** [comment]
this seems to be a stride bug... has to be fixed there. maybe better to open the issue on their repository.

**Comment by antongit** [comment]
Turns out, that this is not a Stride's bug, but VL.Stride's LookAt calculation here (Up Vector is (0,1,0)):

![image](https://user-images.githubusercontent.com/1189037/99093330-9f3f0780-25d2-11eb-9b3e-a801b79ecdbd.png)

**Comment by seltzdesign** [comment]
I came across the same issue today and fixed it like this:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6575829/216462913-9c06bba4-cf3e-4fc5-853b-5d510d16f09e.png">

As the direction of the light approaches the up vector it switches the up vector of the camera. Rotation around the direction of the spotlight shouldn't matter as long as it's always circular.
