### ISSUE TITLE
TextureWriter crashes vvvv when using unsupported texture format

### ISSUE THREAD

**Issue by azeno** [vvvv/VL.Stride#358]
- Use the patch as linked in #357 
- Switch format to B8G8R8X8_UNorm_SRGB
- Add a TextureWriter and try to write out a png -> boom

**Comment by azeno** [comment]
Causes  access violation in `Stride.Graphics.StandardImageHelper.SaveFromMemory` - the code needs some format checks.

**Comment by tebjan** [comment]
Format checks could be done on our end before calling the method. needs an investigation into which ones actually work...

**Comment by azeno** [comment]
Fixed in [upstream](https://github.com/stride3d/stride/commit/a0e37a0800b1fc9871f083e0eda26a2c58fb438e) as well as added check to our save method (which can be removed once we update to a newer Stride).
