### ISSUE TITLE
Auto consume and set "TexelSize" inputs

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#378]
These inputs show up as soon as one inherits from the Texturing base shader.
We could figure out which texture is set and set the corresponding texture input automatically.

**Comment by azeno** [comment]
I believe this is already handled by TextureFX nodes - using ImageEffect internally taking care of it. So can you be a little more specific please?

**Comment by tebjan** [comment]
Yes, it was showing up for the draw and compute shaders as well. but I think I fixed it already. PR incoming.
