### ISSUE TITLE
TextureFX color inputs behave differently when connected to io-box

### ISSUE THREAD

**Issue by bj-rn** [vvvv/VL.Stride#383]
Tested with _2020.3.0-0128_.

![Color](https://user-images.githubusercontent.com/1632591/103273841-2e07b800-49b8-11eb-9654-48f83ea663a4.gif)
![image](https://user-images.githubusercontent.com/1632591/103274037-96569980-49b8-11eb-984a-95f3d254c698.png)

[ColorDemo.zip](https://github.com/vvvv/VL.Stride/files/5750219/ColorDemo.zip)

**Comment by azeno** [comment]
Puh, tough one. The color stored in an IO box is in gamma space. Inside shaders we work in linear space. Therefor when uploading the color it gets [transformed](https://github.com/vvvv/VL.Stride/blob/develop/packages/VL.Stride.Runtime/src/Rendering/Effects/EffectPins.cs#L215) from gamma to linear space. So far so good. However when [reading](https://github.com/vvvv/VL.Stride/blob/develop/packages/VL.Stride.Runtime/src/Rendering/Effects/EffectPins.cs#L54) the default values from the shader source code we currently don't apply the reverse transformation (linear to gamma) - should we? It would mean that the values displayed in the tooltip would differ from those written in the shader. But maybe the tooltip should also say that it assumes the color to be in gamma space?

@gregsn Any thoughts on this?
