### ISSUE TITLE
Create Shader from NodeBrowser / Template

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Stride#467]
* in nodebrowser hover desired shader: tooltip shows: press ctrl click to clone -> now choose name

-> file of selected shader is copied to local /shader folder and renamed (file and in file)

**Comment by tebjan** [comment]
Steps:
* sketch window/dialogue/wizard UI to clone a shader/node
  * get the current document
  * get available nodes to clone
  * enter name/category
  * copy file with modifications next to the current doc
* add a case for extensions on drop -> call extension
* add a callback for context menu?
* add a callback for node browser entry click, pass context (position, name, doc)

**Comment by joreg** [comment]
- most likely, after creating a shader, it will be edited right away
- therefore the extension should offer to open the file immediately
  - check which is installed: vs, vs code, sublime and offer those as choices
  - in case of vs code and sublime mention the required addons, as mentioned here: https://thegraybook.vvvv.org/reference/libraries/3d/editing-shaders.html#syntax-highlighting
  - in case of vs, also check if vs-stride extension is installed, otherwise it doesn't make sense. if it is not installed, mention how to install it via the main stride installer
  - when opening via vs, also copy the EditShaders.sln, as explained here: https://thegraybook.vvvv.org/reference/libraries/3d/editing-shaders.html#error-reporting

**Comment by joreg** [comment]
- [ ] API to get all shader (file)names (globally) to not allow clashing names
-
