### ISSUE TITLE
Pin order sometimes wrong and SetValue calls the wrong pin

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#483]
see forum: https://discourse.vvvv.org/t/exported-project-runs-only-on-one-pc/19426

this can be reproduced with the patch Reference Overview Mixers from the TextureFX category. unfortunately, it is not possible to debug the factory part of the exported app. so it is not clear where the node gets created in the wrong way.

**Comment by joreg** [comment]
@tebjan is this related? https://discourse.vvvv.org/t/2020-4-0178-replacing-a-blur-by-blurglow-throws-exception-when-connecting-an-iobox/19613

**Comment by tebjan** [comment]
this issue is fixed, alex from m-box confirmed it. i will check whether the node replace issue is related and fixed as well.

**Comment by tebjan** [comment]
this is fixed now.
