### ISSUE TITLE
Restructure EffectShaderNodes

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#495]
this file is getting very hard to work with. there is bad editor support because of all the nested functions and closures.
@azeno do you have ideas how we can structure this better so we get full visual studio convenience back?

**Comment by azeno** [comment]
Well as a first step we could split it up in several files using the `partial` keyword. Like `EffectShaderNodes.ShaderFX.cs`, `EffectShaderNodes.TextureFX.cs` etc. So you can quickly navigate to the parts you work on.

The closures/nested methods allow to add state and new arguments easily. Without them we'd need to introduce a class for each of them - have the feeling of a lot of boiler plate...

**Comment by tebjan** [comment]
yes, I've split it into files and lifted the main methods up, it needs a few more arguments, but at least the method drop-down works now.
