### ISSUE TITLE
Make sure EditShaders.sln always has the right version referenced

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#559]
set the $(Version) variable during the build... for example. otherwise, visual studio will show an error but the shader is valid, which should never happen.

**Comment by joreg** [comment]
EditShaders.csproj:
- set correct targetframework: net6.0
- packagereference for vl.stride.runtime: version: take from VL.Core.VersionUtils (via stringreplace)

NuGet.config:
- https...

**Comment by azeno** [comment]
@antongit You can now safely use the `VersionUtils.Current` property. It now matches the nuget version of ours.

![image](https://user-images.githubusercontent.com/573618/215086907-b9114228-4000-4ce4-8a7c-84ab108c96e4.png)
