### ISSUE TITLE
Source repo doesnt work in 2022.5

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#582]
Following the readme description, the source package binaries don't get loaded.

When checking the modules window in visual studio, it always shows that the VL.Stride binaries next to vvvv.exe are loaded. If they are deleted, vvvv.exe doesn't start at all.

What is the new way to check out VL.Stride locally and use it as a source repo?

**Comment by azeno** [comment]
Hm I think it was configured to overwrite the dlls in the lib folder - and that lib folder doesn't exist anymore in 2022.5, so I guess you simply need to remove the lib part here:
https://github.com/vvvv/VL.Stride/blob/preview/2022.5/packages/VL.Stride/src/VL.Stride.csproj#L16

**Comment by tebjan** [comment]
So this should be the path where the vvvv.exe is that is used? In this case it is a custom vvvv folder configured with all project dependencies.

**Comment by tebjan** [comment]
That works almost, but vvvv.exe complains that the referenced dll is a different one:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/1094716/199529943-5019125e-9d9a-4227-b765-c21efd8cb6d5.png">

Can the version be set somewhere?
