### ISSUE TITLE
Provide nodeset for VR

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#95]
should just be a forward and a setter on the forward renderer:
https://doc.stride3d.net/latest/en/manual/virtual-reality/enable-vr.html

**Comment by tebjan** [comment]
need a fix in Stride.

**Comment by tebjan** [comment]
PR done: https://github.com/stride3d/stride/pull/982

**Comment by azeno** [comment]
138ad9e54eddf16402d2f5d6dc7f1c7d14df1866 reverts above commit. So keep this open until new Stride packages are available.
